-- ═══════════════════════════════════════════════════════════════════════
-- MIGRATION LEDGER BASELINE
-- Generated by backend/scripts/generate-migration-baseline.js on 2026-09-10T02:44:39.425Z
--
-- This RECORDS migrations as applied. It does NOT run them. Paste it into the
-- Supabase SQL editor once, on a database whose schema is already current.
--
-- Marks applied : 122 migrations, through 20260910010000
-- Leaves pending: 1 (20260911000000)
--
-- AFTERWARDS, PROVE IT: run `supabase db diff` (or
-- `node backend/scripts/audit-schema.js`). A clean result means the baseline was
-- honest. A dirty one names exactly what was never applied — apply that by hand,
-- because the CLI will now skip it forever.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- The ledger lives in its own schema and may not exist on a database that has
-- never been touched by the CLI. Creating it here is what makes this safe to run
-- before the first `db push` rather than after it.
CREATE SCHEMA IF NOT EXISTS supabase_migrations;

CREATE TABLE IF NOT EXISTS supabase_migrations.schema_migrations (
  version    TEXT PRIMARY KEY,
  statements TEXT[],
  name       TEXT
);

-- `statements` is left NULL on purpose: it is the CLI's record of what it ran,
-- and it ran nothing. Filling it with the file contents would claim otherwise.
--
-- ON CONFLICT DO NOTHING so this is re-runnable and so it can never overwrite a
-- row the CLI wrote itself.
INSERT INTO supabase_migrations.schema_migrations (version, name) VALUES
  ('20260607000000', 'init_schema'),
  ('20260607100000', 'schema_completion'),
  ('20260607100001', 'rls_hardening'),
  ('20260607100002', 'qa_stress_test_fixes'),
  ('20260609000000', 'sms_ledger_idempotency'),
  ('20260610000000', 'auth_otp'),
  ('20260610100000', 'security_hardening'),
  ('20260610200000', 'performance_indexes'),
  ('20260610300000', 'cleanup_stored_functions'),
  ('20260611000000', 'rls_security_fix'),
  ('20260611000001', 'missing_rpc_functions'),
  ('20260611100000', 'search_path_hardening'),
  ('20260611200000', 'audit_fixes'),
  ('20260611300000', 'registration_otp'),
  ('20260612', 'add_template_data'),
  ('20260614000000', 'update_unassign_seat'),
  ('20260615000000', 'prd_updates'),
  ('20260615100000', 'notification_preferences'),
  ('20260615200000', 'event_qr_persistence'),
  ('20260615300000', 'seating_force_override'),
  ('20260615400000', 'rls_pii_lockdown'),
  ('20260616000000', 'seating_elements_scale'),
  ('20260616100000', 'atomic_sms_purchase'),
  ('20260616200000', 'party_size_bound'),
  ('20260616300000', 'manual_payment_methods'),
  ('20260617000000', 'field_type_expansion'),
  ('20260618000000', 'event_review_gate'),
  ('20260618100000', 'rsvp_email_invitations'),
  ('20260619000000', 'rbac_foundation'),
  ('20260619010000', 'sessions_security'),
  ('20260619020000', 'admin_audit'),
  ('20260619040000', 'subscriptions'),
  ('20260619050000', 'credit_packages'),
  ('20260619120000', 'payment_refunds'),
  ('20260619130000', 'overview_finance'),
  ('20260620000000', 'submit_rsvp_rpc'),
  ('20260624000000', 'event_plan_tier'),
  ('20260625000000', 'email_automation'),
  ('20260626000000', 'sms_multi_credit'),
  ('20260627000000', 'sms_campaign_jobs'),
  ('20260628000000', 'sms_delivery_reconcile'),
  ('20260629000000', 'submit_rsvp_reject_resubmit'),
  ('20260701000000', 'submit_rsvp_caps_limits'),
  ('20260702000000', 'feature_payment_gate'),
  ('20260703000000', 'finance_rollup_fix'),
  ('20260704000000', 'submit_rsvp_phone_dedupe'),
  ('20260705000000', 'guest_experience_rebuild'),
  ('20260705500000', 'fold_in_untracked_schema'),
  ('20260706000000', 'submit_rsvp_auto_merge'),
  ('20260707000000', 'profile_branding'),
  ('20260708000000', 'event_comp_reason'),
  ('20260708000001', 'landing_stats'),
  ('20260709000000', 'submit_rsvp_concurrency_fix'),
  ('20260709000001', 'lockdown_super_admin_config_rls'),
  ('20260710000000', 'submit_rsvp_custom_answer_validation'),
  ('20260711000000', 'companion_detail_fields'),
  ('20260712000000', 'tier_watermark_and_limits'),
  ('20260713000000', 'get_event_parties_rpc'),
  ('20260714000000', 'guest_side_tagging'),
  ('20260715000000', 'remove_companion_detail_fields'),
  ('20260716000000', 'update_party_response_guest_cap'),
  ('20260717000000', 'admin_revenue_consistency_fix'),
  ('20260718000000', 'rsvp_sms_consent'),
  ('20260719000000', 'marketing_forms'),
  ('20260720000000', 'seating_party_lock_fix'),
  ('20260721000000', 'primary_guest_dietary_notes'),
  ('20260722000000', 'guest_scoped_questions_for_primary'),
  ('20260723000000', 'custom_field_show_condition'),
  ('20260723010000', 'organizer_added_seating_reveal'),
  ('20260724000000', 'deprecate_invitation_seal_images'),
  ('20260725000000', 'fix_declined_guest_rematch'),
  ('20260726000000', 'scrub_legacy_song_request_notes'),
  ('20260727000000', 'backfill_pricing_tier_features'),
  ('20260727000001', 'guest_analytics_composite_indexes'),
  ('20260727100000', 'envelope_reveal_settings'),
  ('20260728000000', 'drop_checkin_actor_fk'),
  ('20260729000000', 'backfill_baseline_tier_features'),
  ('20260730000000', 'contact_submissions_segments'),
  ('20260731000000', 'testimonials'),
  ('20260801000000', 'press_mentions'),
  ('20260802000000', 'referral_program'),
  ('20260803000000', 'referral_credit_holds'),
  ('20260804000000', 'blog'),
  ('20260805000000', 'landing_stats_live_source'),
  ('20260806000000', 'contact_inquiries_admin'),
  ('20260807000000', 'promo_codes'),
  ('20260808000000', 'drop_auth_users_actor_fks'),
  ('20260809000000', 'sms_compliance'),
  ('20260810000000', 'sms_optin_submissions'),
  ('20260811000000', 'pricing_tier_enterprise_plus'),
  ('20260811010000', 'sms_consent_log'),
  ('20260812000000', 'no_kids_allowed'),
  ('20260812010000', 'host_sms_consent_attestation'),
  ('20260813000000', 'collect_dietary_restrictions'),
  ('20260814000000', 'checkin_offline_foundation'),
  ('20260815000000', 'checkin_guest_delta_and_controls'),
  ('20260816000000', 'seating_zone_shapes'),
  ('20260817000000', 'rsvp_companions_name_only'),
  ('20260818000000', 'sms_addon'),
  ('20260818000002', 'tier_identity'),
  ('20260819000000', 'sms_pricing_config'),
  ('20260820000000', 'sms_usage_and_limits'),
  ('20260821000000', 'sms_organizer_optin_and_perf'),
  ('20260822000000', 'sms_rebuild'),
  ('20260823000000', 'sms_rsvp_confirmation'),
  ('20260824000000', 'retire_wedding_engagement_templates'),
  ('20260825000000', 'printed_invitations'),
  ('20260826000000', 'shop_usd_and_moq'),
  ('20260827000000', 'shop_category_cover'),
  ('20260828000000', 'organizer_timezone'),
  ('20260829000000', 'seating_reminder_weight'),
  ('20260830000000', 'assign_checkin_app_feature'),
  ('20260830000001', 'assign_analytics_advanced_feature'),
  ('20260830000002', 'reconcile_watermark_switches'),
  ('20260830000003', 'white_label'),
  ('20260830000004', 'checkin_undo_by_ref'),
  ('20260831000000', 'checkin_web_upsert'),
  ('20260901000000', 'sms_templates_and_event_purge'),
  ('20260902000000', 'free_trial'),
  ('20260903000000', 'seed_trial_plan'),
  ('20260910000000', 'fk_and_hotpath_indexes'),
  ('20260910010000', 'anon_surface_lockdown')
ON CONFLICT (version) DO NOTHING;

-- What the ledger looks like afterwards.
SELECT count(*) AS recorded, min(version) AS oldest, max(version) AS newest
FROM supabase_migrations.schema_migrations;

COMMIT;
